# Use postgres/example user/password credentials
version: '3.1'

services:

  postgres_001:
    image: postgres
    env_file: ./.env
    container_name: ibm_postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
  
  nodejs_001:
    build:
      context: ./retobase-nodejs
    container_name: 'ibm_nodejs'
    restart: 'always'
    depends_on:
      - postgres_001
    ports:
      - "${NODE_PORT}:4000"
    stdin_open: true
    tty: true

  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "${NGINX_PORT}:80"

  
    